### ISSUE TITLE
UinputError (NotFound)

### ISSUE THREAD

**Issue by maltesa** [samvel1024/kbct#1]
Hi,

First of all. Thank you for the great tool. 

I'm having trouble running kbct on my notebook without an external keyboard connected. This is what I run and the error I receive:
```bash
-> % sudo kbct remap --config /home/malte/dotfiles/kbct/config.yml
 INFO  kbct > Starting kbct event loop, pid=4038
thread 'main' panicked at 'Could not capture keyboard: UinputError(NotFound)', src/main.rs:212:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is my config:
```yaml
- keyboards: ["Keychron Keychron K3", "AT Translated Set 2 keyboard"]
  keymap:
  layers:
    - modifiers: ["capslock"]
      keymap:
        h: left
        j: down
        k: up
        l: right
        u: pageup
        p: pagedown
        i: home
        o: end
        comma: delete

```

This is what evtest says, so the device name should be correct:
```
/dev/input/event3:      AT Translated Set 2 keyboard
```

I used kbct yesterday with my external keyboard connected and the same config and it worked flawlessly.
Do you have any idea what I am doing wrong? I already removed the K3 device from the config and double checked the device name for my internal keyboard.
