### ISSUE TITLE
Bind key to combination

### ISSUE THREAD

**Issue by Termack** [samvel1024/kbct#13]
Hello, there are some characters in my keyboard that i can only get by using a combination of others.

So I would like to know if there is a way to create a bind to a combination of keys, something like this for example:

```
- keyboards: [ "AT Translated Set 2 keyboard"]

  layers:
    - modifiers: ['rightshift']
      keymap:
        apostrophe: rightalt + q
```
