### ISSUE TITLE
Available modifiers

### ISSUE THREAD

**Issue by yz47** [samvel1024/kbct#3]
Just wondering the full list of supported modifiers. I understand I can search for some keynames in https://gist.githubusercontent.com/samvel1024/02e5675e04f9d84f098e98bcd0e1ea12/raw/e18d950ce571b4ff5c832cc06406e9a6afece132/keynames.txt, but some keys that I'd like to use are not in there, for example, `hyper`, `altgr`, `iso_level3_shift`, and `iso_level5_shift`. Thanks!

**Comment by yz47** [comment]
For keys that are in the link, for example, `rightmeta`, I couldn't seem to be able to use it as a modifier. For example, the following doesn't work: 

```
- keyboards: [ "AT Translated Set 2 keyboard"]
  keymap:
    rightalt: rightmeta
  layers:
      - modifiers: [ 'rightmeta' ]
      keymap:
        i: up
        j: left
        k: down
        l: right
```

By "doesn't work", I mean there are two issues: 

First, hitting the Right Alt + i doesn't give me "up". 

Second, the Right Alt key doesn't seem to be mapped to `rightmeta`. With kbct running with this config, I ran `xev` and hit the Right Alt key, but `xev` suggests it's `Super_R`.
