### ISSUE TITLE
`ctrl` + `enter` and `ctrl` + `backspace` don't work after remapping `fn` to `ctrl`

### ISSUE THREAD

**Issue by ElSamhaa** [samvel1024/kbct#32]
Otherwise, other combinations work as expected, i.e `ctrl` + `c`, `ctrl` + `l` ...

`/etc/kbct.yaml` referenced in a systemd service definition:

```yaml
- keyboards: [ 'Apple Inc. Apple Internal Keyboard / Trackpad' ]
  keymap:
    fn: leftctrl
    leftmeta: leftalt
    leftalt: leftmeta
    leftctrl: fn
    ejectcd: delete
    rightalt: rightctrl
    rightmeta: rightalt
```
