### ISSUE TITLE
Disable a key

### ISSUE THREAD

**Issue by dlight** [samvel1024/kbct#39]
Can kbct disable a key, instead of mapping it to something else?

**Comment by seandlg** [comment]
Yes, this is possible, e.g.

```yaml
- keyboards: [ "AT Translated Set 2 keyboard"]
  keymap:
    rightalt: reserved
```
